config/routes.rb
Rails.application.routes.draw do
  root "rooms#home"

  get "rooms/get", to: "rooms#get"
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  before_create :set_code

  private
  def set_code
    attempts = 0
    code_length = 4
    code = SecureRandom.alphanumeric(code_length)

    while Room.exists?(code: code)
      attempts += 1
      if attempts > 10
        code_length += 1
        attempts = 0
      end
      code = SecureRandom.alphanumeric(code_length)
    end

    self.code = code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end
  
  def home
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end
  
  def get
    room = Room.find_by(code: get_room_params[:room_code])
    if room.present?
      respond_to do |format|
        format.html { redirect_to room_url(room), notice: "Successfully entered room." }
        format.json { render json: { message: "Successfully entered room." }, status: 200 }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path, alert: "Room is unavailable." }
        format.json { render json: { message: "Room is unavailable." }, status: :unprocessable_entity }
      end
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      begin
        @room = Room.find(params[:id])
      rescue
        respond_to do |format|
          format.html { redirect_to root_path, alert: "Room is unavailable." }
          format.json { render json: { message: "Room is unavailable." }, status: :unprocessable_entity }
        end
      end
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.fetch(:room, {})
    end
   
    # Only allow a list of trusted parameters through.
    def get_room_params
      params.permit(:room_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhosThatPokemon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="grid justify-items-center mt-16">
      <%= yield %>
    </main>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>" class="mt-4">
  Room code: <%= room.code %>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/home.html.erb
<div class="text-3xl">Who's that Pokémon?!</div>
<div class="mt-4">Challenge your friends and find out who's the Pokémon master</div>

<div class="flex items-center space-x-4 mt-8">
  <%= form_with url: rooms_path do |form| %>
    <%= form.submit "Create a New Room", class: "cursor-pointer p-2 px-4 bg-blue-300 rounded" %>
  <% end %> 

  <p>or</p>


  <%= form_with url: rooms_get_path, method: "get" do |form| %>
    <%= form.text_field :room_code %>
    <%= form.submit "Enter Room", class: "cursor-pointer p-2 px-4 bg-blue-300 rounded" %>
  <% end %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<p class="text-3xl">You're in a room!</p>

<%# renders room partial %>
<%= render @room %>

<div class="flex space-x-4 mt-8">
  <%= link_to "Edit this room", edit_room_path(@room), class: "cursor-pointer p-2 px-4 bg-blue-300 rounded" %>
  <%= link_to "Leave Room", root_path, class: "cursor-pointer p-2 px-4 bg-blue-300 rounded" %>

  <%= button_to "Destroy this room", @room, method: :delete, class: "cursor-pointer p-2 px-4 bg-red-300 rounded" %>
</div>